import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillGithub, AiFillLinkedin,AiFillCopyrightCircle, AiFillInstagram} from 'react-icons/ai';
// Use standard <img> for consistent SSR/CSR markup
import Head from 'next/head'
import { useState, useEffect } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [typewriterText, setTypewriterText] = useState('');

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (mounted) {
      const text = "Hi! I'm Ayushman.";
      let currentIndex = 0;
      let isDeleting = false;
      let timeout;

      const type = () => {
        if (isDeleting) {
          if (currentIndex > 0) {
            currentIndex--;
            setTypewriterText(text.slice(0, currentIndex));
            timeout = setTimeout(type, 50);
          } else {
            isDeleting = false;
            timeout = setTimeout(type, 500);
          }
        } else {
          if (currentIndex < text.length) {
            currentIndex++;
            setTypewriterText(text.slice(0, currentIndex));
            timeout = setTimeout(type, 100);
          } else {
            isDeleting = true;
            timeout = setTimeout(type, 2000);
          }
        }
      };

      timeout = setTimeout(type, 100);
      return () => clearTimeout(timeout);
    }
  }, [mounted]);

  return (
  <div className={mounted && darkMode ? "dark" : ""} suppressHydrationWarning>
      <Head>
        <title>Ayushman's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=" min-h-screen ">
          <nav className="py-5 mb-6 flex justify-between">
            <h1 className='text-xl font-burtons dark:text-white font-semibold'>Portfolio</h1>
            <ul className='flex items-center'>
              <li>
                <button
                  onClick={() => setDarkMode(!darkMode)}
                  className="relative inline-flex h-8 w-14 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-offset-2 dark:focus:ring-offset-gray-900"
                  style={{
                    backgroundColor: mounted && darkMode ? '#1f2937' : '#e5e7eb',
                  }}
                  aria-label="Toggle dark mode"
                >
                  <span
                    className="inline-block h-7 w-7 transform rounded-full bg-white shadow-lg transition-transform duration-300"
                    style={{
                      transform: mounted && darkMode ? 'translateX(28px)' : 'translateX(2px)',
                    }}
                  >
                    <div className="flex h-full w-full items-center justify-center">
                      {mounted && darkMode ? (
                        <svg className="h-4 w-4 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l-2.12-2.12a1 1 0 00-1.414 1.414l2.12 2.12a1 1 0 001.414-1.414zM2.05 6.464a1 1 0 000 1.414l1.414-1.414A1 1 0 002.05 6.464zm14.14 0a1 1 0 00-1.414 0l-1.414 1.414a1 1 0 001.414 1.414l1.414-1.414a1 1 0 000-1.414zM2.464 2.05a1 1 0 00-1.414 0A1 1 0 002.05 3.464l1.414-1.414a1 1 0 00-1.414-1.414zm12.02 12.02a1 1 0 001.414 0 1 1 0 00-1.414-1.414l-1.414 1.414a1 1 0 001.414 1.414zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM2.05 13.536a1 1 0 110 1.414l1.414 1.414a1 1 0 101.414-1.414l-1.414-1.414a1 1 0 01-1.414 0zm0-2.122a1 1 0 100 1.414l1.414-1.414a1 1 0 10-1.414-1.414l-1.414 1.414z" clipRule="evenodd" />
                        </svg>
                      ) : (
                        <BsFillMoonStarsFill className="h-4 w-4 text-gray-600" />
                      )}
                    </div>
                  </span>
                </button>
              </li>
              <li>
              <a className='bg-gradient-to-r from-cyan-500 to-cyan-600 text-white px-4 py-2 rounded-lg ml-8 hover:shadow-lg hover:scale-105 transition-all duration-300'
               href="https://drive.google.com/file/d/1QeTo_QL_E4-tHdJ525jMFgknF1wjvfVP/view?usp=sharing">Resume</a>
            </li>
            </ul>
          </nav>
          <div className="flex flex-col md:flex-row items-center justify-center gap-10 md:gap-20 py-5 pt-20">
            <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 overflow-hidden md:h-96 md:w-96 animate-float will-change-transform hover:scale-105 transition-transform duration-500 pop-out' tabIndex={0}>
              <img src="/dev-ed-wave.png" alt="Dev" className="object-cover w-full h-full" />
            </div>
            <div className="flex flex-col items-center md:items-start">
              <div className='text-center md:text-left p-5 md:p-10'>
                <h2 className='text-3xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'>{typewriterText}<span className="animate-pulse">|</span></h2>
                <h3 className='text-2xl py-2 font-medium md:text-3xl dark:text-gray-300'>Frontend Developer and Designer</h3>
                <p className='text-md py-4 leading-8 text-gray-800 font-semibold max-w-lg mx-auto md:mx-0 dark:text-white'>I design and code beautifully simple ideas of someones's imagination, and I love what I do.</p>
                <p className='text-xl pt-2 font-medium  dark:text-gray-200'>Living, learning, & leveling up one day at a time.</p>
              </div>
              <div className='text-5xl flex justify-center md:self-center gap-8 py-3 text-gray-700 dark:text-white'>
                <a aria-label="LinkedIn" href="https://www.linkedin.com/in/ayushman-dutt-pandey-741b391a4/" className="inline-flex items-center justify-center p-3 rounded-full bg-white/5 dark:bg-white/5 text-current shadow-sm hover:shadow-2xl transform transition-transform duration-300 hover:-translate-y-1 hover:scale-110 hover:rotate-6 focus:outline-none focus:ring-4 focus:ring-teal-200/30">
                  <AiFillLinkedin />
                </a>

                <a aria-label="Instagram" href="https://www.instagram.com/ayushmanduttpandey/" className="inline-flex items-center justify-center p-3 rounded-full bg-white/5 dark:bg-white/5 text-current shadow-sm hover:shadow-2xl transform transition-transform duration-300 hover:-translate-y-1 hover:scale-110 hover:-rotate-6 focus:outline-none focus:ring-4 focus:ring-teal-200/30">
                  <AiFillInstagram />
                </a>

                <a aria-label="GitHub" href="https://github.com/Ayushmanpandey" className="inline-flex items-center justify-center p-3 rounded-full bg-white/5 dark:bg-white/5 text-current shadow-sm hover:shadow-2xl transform transition-transform duration-300 hover:-translate-y-1 hover:scale-110 hover:rotate-6 focus:outline-none focus:ring-4 focus:ring-teal-200/30">
                  <AiFillGithub />
                </a>
              </div>
            </div>
          </div>
        </section>

        {/* <!--- SERVICES SECTION ---!> */}
        <section className='relative py-0 px-0'>
          {/* Decorative background element */}
          <div className='absolute -left-20 top-20 w-72 h-72 bg-teal-300 dark:bg-teal-900/30 rounded-full blur-3xl opacity-20 pointer-events-none'></div>
          <div className='absolute -right-20 bottom-40 w-96 h-96 bg-cyan-300 dark:bg-cyan-900/30 rounded-full blur-3xl opacity-20 pointer-events-none'></div>
          
          <div className='relative z-10'>
            <div className='text-center mb-10'>
              <span className='inline-block px-4 py-2 bg-teal-100 dark:bg-teal-900/40 text-teal-600 dark:text-teal-300 rounded-full text-sm font-semibold mb-4'>EXPERTISE</span>
              <h2 className='text-5xl md:text-6xl font-bold dark:text-white mb-4'>What I <span className='bg-gradient-to-r from-teal-500 to-cyan-500 bg-clip-text text-transparent'>Create</span></h2>
              <p className='text-xl text-gray-600 dark:text-gray-400 max-w-2xl mx-auto'>Crafting beautiful digital experiences with modern technologies and creative problem-solving</p>
              <div className='w-20 h-1 bg-gradient-to-r from-teal-500 to-cyan-500 mx-auto mt-8'></div>
            </div>

            <div className='grid grid-cols-1 md:grid-cols-3 gap-8 lg:gap-10 mb-10'>
              {/* SERVICE CARD 1 - Responsive Design */}
              <div className='service-card group relative'>
                <div className='absolute inset-0 bg-gradient-to-r from-teal-500/20 to-cyan-500/20 dark:from-teal-500/10 dark:to-cyan-500/10 rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-opacity duration-300'></div>
                <div className='relative p-10 rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 shadow-lg hover:shadow-2xl transition-all duration-300 h-full transform group-hover:scale-105'>
                  <div className='flex items-center justify-center w-16 h-16 bg-gradient-to-br from-teal-500 to-cyan-500 rounded-xl mb-6 group-hover:scale-110 transition-transform'>
                    <span className='text-2xl'>📱</span>
                  </div>
                  <h3 className='text-2xl font-bold text-gray-900 dark:text-white mb-3'>Responsive Design</h3>
                  <p className='text-gray-600 dark:text-gray-400 mb-4 leading-relaxed'>Websites that look perfect on every device - from desktop to mobile - ensuring seamless user experiences across all screen sizes.</p>
                  <ul className='space-y-2 text-sm text-gray-600 dark:text-gray-400'>
                    <li className='flex items-center'><span className='inline-block w-2 h-2 bg-teal-500 rounded-full mr-2'></span>Mobile-first approach</li>
                    <li className='flex items-center'><span className='inline-block w-2 h-2 bg-teal-500 rounded-full mr-2'></span>Cross-browser compatible</li>
                    <li className='flex items-center'><span className='inline-block w-2 h-2 bg-teal-500 rounded-full mr-2'></span>Performance optimized</li>
                  </ul>
                </div>
              </div>

              {/* SERVICE CARD 2 - Web & Frontend */}
              <div className='service-card group relative'>
                <div className='absolute inset-0 bg-gradient-to-r from-teal-500/20 to-cyan-500/20 dark:from-teal-500/10 dark:to-cyan-500/10 rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-opacity duration-300'></div>
                <div className='relative p-10 rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 shadow-lg hover:shadow-2xl transition-all duration-300 h-full transform group-hover:scale-105'>
                  <div className='flex items-center justify-center w-16 h-16 bg-gradient-to-br from-teal-500 to-cyan-500 rounded-xl mb-6 group-hover:scale-110 transition-transform'>
                    <span className='text-2xl'>💻</span>
                  </div>
                  <h3 className='text-2xl font-bold text-gray-900 dark:text-white mb-3'>Web Development</h3>
                  <p className='text-gray-600 dark:text-gray-400 mb-4 leading-relaxed'>Full-featured frontend development using modern frameworks and technologies to bring your ideas to life in the browser.</p>
                  <ul className='space-y-2 text-sm text-gray-600 dark:text-gray-400'>
                    <li className='flex items-center'><span className='inline-block w-2 h-2 bg-teal-500 rounded-full mr-2'></span>React.js & Next.js</li>
                    <li className='flex items-center'><span className='inline-block w-2 h-2 bg-teal-500 rounded-full mr-2'></span>Tailwind & Bootstrap</li>
                    <li className='flex items-center'><span className='inline-block w-2 h-2 bg-teal-500 rounded-full mr-2'></span>Modern JavaScript</li>
                  </ul>
                </div>
              </div>

              {/* SERVICE CARD 3 - UI Design */}
              <div className='service-card group relative'>
                <div className='absolute inset-0 bg-gradient-to-r from-teal-500/20 to-cyan-500/20 dark:from-teal-500/10 dark:to-cyan-500/10 rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-opacity duration-300'></div>
                <div className='relative p-10 rounded-2xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 shadow-lg hover:shadow-2xl transition-all duration-300 h-full transform group-hover:scale-105'>
                  <div className='flex items-center justify-center w-16 h-16 bg-gradient-to-br from-teal-500 to-cyan-500 rounded-xl mb-6 group-hover:scale-110 transition-transform'>
                    <span className='text-2xl'>🎨</span>
                  </div>
                  <h3 className='text-2xl font-bold text-gray-900 dark:text-white mb-3'>UI/UX Design</h3>
                  <p className='text-gray-600 dark:text-gray-400 mb-4 leading-relaxed'>Beautiful and intuitive user interfaces designed to delight users with thoughtful interactions and stunning visuals.</p>
                  <ul className='space-y-2 text-sm text-gray-600 dark:text-gray-400'>
                    <li className='flex items-center'><span className='inline-block w-2 h-2 bg-teal-500 rounded-full mr-2'></span>Figma & Adobe XD</li>
                    <li className='flex items-center'><span className='inline-block w-2 h-2 bg-teal-500 rounded-full mr-2'></span>Web & App Design</li>
                    <li className='flex items-center'><span className='inline-block w-2 h-2 bg-teal-500 rounded-full mr-2'></span>Design Systems</li>
                  </ul>
                </div>
              </div>
            </div>

            {/* Tech Stack Section */}
            <div className='bg-gradient-to-r from-teal-50 to-cyan-50 dark:from-teal-900/20 dark:to-cyan-900/20 rounded-2xl p-12 border border-teal-200 dark:border-teal-800'>
              <h3 className='text-3xl font-bold text-gray-900 dark:text-white mb-10 text-center'>Tech Stack</h3>
              <div className='grid grid-cols-2 md:grid-cols-4 gap-6'>
                <div className='flex flex-col items-center p-4 rounded-xl bg-white dark:bg-gray-800 shadow-md hover:shadow-lg hover:scale-110 transition-all duration-300 cursor-pointer group'>
                  <span className='text-4xl mb-2 group-hover:scale-125 transition-transform'>⚛️</span>
                  <span className='font-semibold text-sm text-gray-700 dark:text-gray-300 text-center'>React</span>
                </div>
                <div className='flex flex-col items-center p-4 rounded-xl bg-white dark:bg-gray-800 shadow-md hover:shadow-lg hover:scale-110 transition-all duration-300 cursor-pointer group'>
                  <span className='text-4xl mb-2 group-hover:scale-125 transition-transform'>▲</span>
                  <span className='font-semibold text-sm text-gray-700 dark:text-gray-300 text-center'>Next.js</span>
                </div>
                <div className='flex flex-col items-center p-4 rounded-xl bg-white dark:bg-gray-800 shadow-md hover:shadow-lg hover:scale-110 transition-all duration-300 cursor-pointer group'>
                  <span className='text-4xl mb-2 group-hover:scale-125 transition-transform'>🎨</span>
                  <span className='font-semibold text-sm text-gray-700 dark:text-gray-300 text-center'>Tailwind</span>
                </div>
                <div className='flex flex-col items-center p-4 rounded-xl bg-white dark:bg-gray-800 shadow-md hover:shadow-lg hover:scale-110 transition-all duration-300 cursor-pointer group'>
                  <span className='text-4xl mb-2 group-hover:scale-125 transition-transform'>📝</span>
                  <span className='font-semibold text-sm text-gray-700 dark:text-gray-300 text-center'>JavaScript</span>
                </div>
                <div className='flex flex-col items-center p-4 rounded-xl bg-white dark:bg-gray-800 shadow-md hover:shadow-lg hover:scale-110 transition-all duration-300 cursor-pointer group'>
                  <span className='text-4xl mb-2 group-hover:scale-125 transition-transform'>🔧</span>
                  <span className='font-semibold text-sm text-gray-700 dark:text-gray-300 text-center'>HTML/CSS</span>
                </div>
                <div className='flex flex-col items-center p-4 rounded-xl bg-white dark:bg-gray-800 shadow-md hover:shadow-lg hover:scale-110 transition-all duration-300 cursor-pointer group'>
                  <span className='text-4xl mb-2 group-hover:scale-125 transition-transform'>🎯</span>
                  <span className='font-semibold text-sm text-gray-700 dark:text-gray-300 text-center'>Figma</span>
                </div>
                <div className='flex flex-col items-center p-4 rounded-xl bg-white dark:bg-gray-800 shadow-md hover:shadow-lg hover:scale-110 transition-all duration-300 cursor-pointer group'>
                  <span className='text-4xl mb-2 group-hover:scale-125 transition-transform'>🐙</span>
                  <span className='font-semibold text-sm text-gray-700 dark:text-gray-300 text-center'>Git</span>
                </div>
                <div className='flex flex-col items-center p-4 rounded-xl bg-white dark:bg-gray-800 shadow-md hover:shadow-lg hover:scale-110 transition-all duration-300 cursor-pointer group'>
                  <span className='text-4xl mb-2 group-hover:scale-125 transition-transform'>🚀</span>
                  <span className='font-semibold text-sm text-gray-700 dark:text-gray-300 text-center'>More</span>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* <!--- ORIGINAL CARDS - REMOVED TO FIT NEW DESIGN ---!> */}
        {/* SECTION - MY WORK */}
        <section className='relative py-10 px-0'>
          {/* Decorative background */}
          <div className='absolute -left-20 -top-20 w-80 h-80 bg-purple-300 dark:bg-purple-900/30 rounded-full blur-3xl opacity-20 pointer-events-none'></div>
          
          <div className='relative z-10'>
            <div className='text-center mb-10'>
              <span className='inline-block px-4 py-2 bg-purple-100 dark:bg-purple-900/40 text-purple-600 dark:text-purple-300 rounded-full text-sm font-semibold mb-4'>PORTFOLIO</span>
              <h2 className='text-5xl md:text-6xl font-bold dark:text-white mb-4'>Featured <span className='bg-gradient-to-r from-purple-500 to-pink-500 bg-clip-text text-transparent'>Projects</span></h2>
              <p className='text-xl text-gray-600 dark:text-gray-400 max-w-2xl mx-auto'>A selection of designs and projects I've created that showcase my skills and creativity</p>
              <div className='w-20 h-1 bg-gradient-to-r from-purple-500 to-pink-500 mx-auto mt-8'></div>
            </div>

            {/* Designs Section */}
            <div className='mb-12'>
              <div className='flex items-center gap-3 mb-12'>
                <div className='w-1 h-8 bg-gradient-to-b from-purple-500 to-pink-500'></div>
                <h3 className='text-3xl font-bold dark:text-white'>UI/UX Design Mockups</h3>
              </div>
              <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6'>
                {/* Project 1 */}
                <div className='group cursor-pointer'>
                  <div className='relative overflow-hidden rounded-2xl h-64 md:h-72 mb-4 pop-out'>
                    <img src="/finalMockupFoodApp.png" alt="Food App" className='w-full h-full object-cover transform transition-transform duration-500 group-hover:scale-110' />
                    <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6'>
                      <div>
                        <h4 className='text-white font-bold text-lg'>Food App UI</h4>
                        <p className='text-gray-300 text-sm'>Mobile App Design</p>
                      </div>
                    </div>
                  </div>
                  <a href='https://github.com/Ayushmanpandey/DesigningProjects/tree/main/Food%20App%20Design%20practice' className='inline-flex items-center justify-center whitespace-nowrap px-6 py-2 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg transition-all duration-300 hover:shadow-lg hover:scale-105 group/btn'>View <span className='ml-2 group-hover/btn:translate-x-1 transition-transform'>→</span></a>
                </div>

                {/* Project 2 */}
                <div className='group cursor-pointer'>
                  <div className='relative overflow-hidden rounded-2xl h-64 md:h-72 mb-4 pop-out'>
                    <img src="/finalMockupMovieApp.png" alt="Movie App" className='w-full h-full object-cover transform transition-transform duration-500 group-hover:scale-110' />
                    <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6'>
                      <div>
                        <h4 className='text-white font-bold text-lg'>Movie App UI</h4>
                        <p className='text-gray-300 text-sm'>Mobile App Design</p>
                      </div>
                    </div>
                  </div>
                  <a href='https://github.com/Ayushmanpandey/DesigningProjects/tree/main/MovieApp%20Figma%20redesign' className='inline-flex items-center justify-center whitespace-nowrap px-6 py-2 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg transition-all duration-300 hover:shadow-lg hover:scale-105 group/btn'>View <span className='ml-2 group-hover/btn:translate-x-1 transition-transform'>→</span></a>
                </div>

                {/* Project 3 */}
                <div className='group cursor-pointer'>
                  <div className='relative overflow-hidden rounded-2xl h-64 md:h-72 mb-4 pop-out'>
                    <img src="/MockupClock.png" alt="Clock Mockup" className='w-full h-full object-cover transform transition-transform duration-500 group-hover:scale-110' />
                    <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6'>
                      <div>
                        <h4 className='text-white font-bold text-lg'>iOS Clock Design</h4>
                        <p className='text-gray-300 text-sm'>iOS App Redesign</p>
                      </div>
                    </div>
                  </div>
                  <a href='https://github.com/Ayushmanpandey/DesigningProjects/tree/main/Figma%20ios%20clock%20redesign' className='inline-flex items-center justify-center whitespace-nowrap px-6 py-2 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg transition-all duration-300 hover:shadow-lg hover:scale-105 group/btn'>View <span className='ml-2 group-hover/btn:translate-x-1 transition-transform'>→</span></a>
                </div>

                {/* Project 4 */}
                <div className='group cursor-pointer'>
                  <div className='relative overflow-hidden rounded-2xl h-64 md:h-72 mb-4 pop-out'>
                    <img src="/mockupEbike.png" alt="Ebike Mockup" className='w-full h-full object-cover transform transition-transform duration-500 group-hover:scale-110' />
                    <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6'>
                      <div>
                        <h4 className='text-white font-bold text-lg'>E-Bike Landing</h4>
                        <p className='text-gray-300 text-sm'>Web Design</p>
                      </div>
                    </div>
                  </div>
                  <a href='https://github.com/Ayushmanpandey/DesigningProjects/tree/main/figmaLandingpageDesign' className='inline-flex items-center justify-center whitespace-nowrap px-6 py-2 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg transition-all duration-300 hover:shadow-lg hover:scale-105 group/btn'>View <span className='ml-2 group-hover/btn:translate-x-1 transition-transform'>→</span></a>
                </div>
              </div>
            </div>

            {/* Frontend Projects Section */}
            <div className='mb-12'>
              <div className='flex items-center gap-3 mb-12'>
                <div className='w-1 h-8 bg-gradient-to-b from-teal-500 to-cyan-500'></div>
                <h3 className='text-3xl font-bold dark:text-white'>Frontend Development</h3>
              </div>
              <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6'>
                {/* Project 1 */}
                <div className='group cursor-pointer'>
                  <div className='relative overflow-hidden rounded-2xl h-64 md:h-72 mb-4 pop-out'>
                    <img src="/finalmockupQuiz.png" alt="Quiz Mockup" className='w-full h-full object-cover transform transition-transform duration-500 group-hover:scale-110' />
                    <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6'>
                      <div>
                        <h4 className='text-white font-bold text-lg'>Quiz App</h4>
                        <p className='text-gray-300 text-sm'>Interactive React App</p>
                      </div>
                    </div>
                  </div>
                  <a href='' className='inline-flex items-center justify-center whitespace-nowrap px-6 py-2 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg transition-all duration-300 hover:shadow-lg hover:scale-105 group/btn'>View <span className='ml-2 group-hover/btn:translate-x-1 transition-transform'>→</span></a>
                </div>

                {/* Project 2 */}
                <div className='group cursor-pointer'>
                  <div className='relative overflow-hidden rounded-2xl h-64 md:h-72 mb-4 pop-out'>
                    <img src="/mockupLogin.png" alt="Login Mockup" className='w-full h-full object-cover transform transition-transform duration-500 group-hover:scale-110' />
                    <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6'>
                      <div>
                        <h4 className='text-white font-bold text-lg'>Login Form</h4>
                        <p className='text-gray-300 text-sm'>Authentication UI</p>
                      </div>
                    </div>
                  </div>
                  <a href='https://ayushmanpandey.github.io/Login-SignupForm/' className='inline-flex items-center justify-center whitespace-nowrap px-6 py-2 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg transition-all duration-300 hover:shadow-lg hover:scale-105 group/btn'>View <span className='ml-2 group-hover/btn:translate-x-1 transition-transform'>→</span></a>
                </div>

                {/* Project 3 */}
                <div className='group cursor-pointer'>
                  <div className='relative overflow-hidden rounded-2xl h-64 md:h-72 mb-4 pop-out'>
                    <img src="/finalPortfolioMockup.png" alt="Portfolio Mockup" className='w-full h-full object-cover transform transition-transform duration-500 group-hover:scale-110' />
                    <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6'>
                      <div>
                        <h4 className='text-white font-bold text-lg'>Portfolio Site</h4>
                        <p className='text-gray-300 text-sm'>Personal Portfolio</p>
                      </div>
                    </div>
                  </div>
                  <a href='https://iamayushmanduttpandey.vercel.app/' className='inline-flex items-center justify-center whitespace-nowrap px-6 py-2 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg transition-all duration-300 hover:shadow-lg hover:scale-105 group/btn'>View <span className='ml-2 group-hover/btn:translate-x-1 transition-transform'>→</span></a>
                </div>

                {/* Project 4 */}
                <div className='group cursor-pointer'>
                  <div className='relative overflow-hidden rounded-2xl h-64 md:h-72 mb-4 pop-out'>
                    <img src="/dashboardmockup.png" alt="Dashboard Mockup" className='w-full h-full object-cover transform transition-transform duration-500 group-hover:scale-110' />
                    <div className='absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-6'>
                      <div>
                        <h4 className='text-white font-bold text-lg'>Dashboard</h4>
                        <p className='text-gray-300 text-sm'>Admin Dashboard</p>
                      </div>
                    </div>
                  </div>
                  <a href='https://ayushmanpandey.github.io/DashboardProj/' className='inline-flex items-center justify-center whitespace-nowrap px-6 py-2 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg transition-all duration-300 hover:shadow-lg hover:scale-105 group/btn'>View <span className='ml-2 group-hover/btn:translate-x-1 transition-transform'>→</span></a>
                </div>
              </div>
            </div>

            {/* CTA Section */}
            <div className='text-center py-12'>
              <p className='text-lg text-gray-600 dark:text-gray-400 mb-6'>Want to explore more of my work?</p>
              <a href="mailto:thisisayushmann@gmail.com" className='inline-flex items-center justify-center px-8 py-4 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg text-lg transition-all duration-300 hover:scale-105 hover:shadow-lg group/cta'>
                <span className='group-hover/cta:-translate-x-1 transition-transform'>✉️</span>
                <span className='ml-3'>Get in Touch</span>
              </a>
            </div>
          </div>
        </section>
        {/* FOOTER */}
        <footer className='relative mt-10 pt-10 pb-10 border-t border-gray-200 dark:border-gray-700'>
          {/* Decorative background */}
          <div className='absolute -right-40 -bottom-20 w-96 h-96 bg-teal-300 dark:bg-teal-900/30 rounded-full blur-3xl opacity-20 pointer-events-none'></div>
          
          <div className='relative z-10'>
            <div className='grid grid-cols-1 md:grid-cols-3 gap-12 mb-12'>
              {/* About Column */}
              <div>
                <h3 className='text-xl font-bold dark:text-white mb-4'>Ayushman</h3>
                <p className='text-gray-600 dark:text-gray-400 leading-relaxed'>
                  A passionate developer and designer creating beautiful digital experiences that make a difference.
                </p>
                <div className='mt-6 flex gap-4'>
                  <a href='https://www.linkedin.com/in/ayushman-dutt-pandey-741b391a4/' className='p-3 rounded-full bg-gradient-to-br from-teal-500/20 to-cyan-500/20 hover:from-teal-500/40 hover:to-cyan-500/40 transition-all duration-300 hover:scale-110 dark:text-white'>
                    <svg className='w-5 h-5' fill='currentColor' viewBox='0 0 24 24'><path d='M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z'/></svg>
                  </a>
                  <a href='https://github.com/Ayushmanpandey' className='p-3 rounded-full bg-gradient-to-br from-teal-500/20 to-cyan-500/20 hover:from-teal-500/40 hover:to-cyan-500/40 transition-all duration-300 hover:scale-110 dark:text-white'>
                    <svg className='w-5 h-5' fill='currentColor' viewBox='0 0 24 24'><path d='M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v 3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z'/></svg>
                  </a>
                  <a href='https://www.instagram.com/ayushmanduttpandey/' className='p-3 rounded-full bg-gradient-to-br from-teal-500/20 to-cyan-500/20 hover:from-teal-500/40 hover:to-cyan-500/40 transition-all duration-300 hover:scale-110 dark:text-white'>
                    <AiFillInstagram className='w-5 h-5' />
                  </a>
                </div>
              </div>

              {/* Quick Links */}
              <div>
                <h4 className='text-lg font-bold dark:text-white mb-6'>Quick Links</h4>
                <ul className='space-y-3'>
                  <li><a href='#' className='text-gray-600 dark:text-gray-400 hover:text-teal-500 dark:hover:text-teal-400 transition-colors'>Home</a></li>
                  <li><a href='#' className='text-gray-600 dark:text-gray-400 hover:text-teal-500 dark:hover:text-teal-400 transition-colors'>Services</a></li>
                  <li><a href='#' className='text-gray-600 dark:text-gray-400 hover:text-teal-500 dark:hover:text-teal-400 transition-colors'>Projects</a></li>
                  <li><a href='#' className='text-gray-600 dark:text-gray-400 hover:text-teal-500 dark:hover:text-teal-400 transition-colors'>Contact</a></li>
                </ul>
              </div>

              {/* Contact */}
              <div>
                <h4 className='text-lg font-bold dark:text-white mb-6'>Get In Touch</h4>
                <p className='text-gray-600 dark:text-gray-400 mb-4'>Have a project in mind? Let's talk!</p>
                <a href="mailto:payushman8@gmail.com" className='inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-cyan-500 to-cyan-600 text-white font-semibold rounded-lg hover:shadow-lg hover:scale-105 transition-all duration-300'>
                  <span>📧</span>
                  <span>Email Me</span>
                </a>
              </div>
            </div>

            {/* Divider */}
            <div className='border-t border-gray-200 dark:border-gray-700 pt-8'>
              <div className='flex flex-col md:flex-row justify-between items-center'>
                <p className='text-gray-600 dark:text-gray-400 text-center md:text-left'>
                  <span className='font-semibold'>©</span> 2024 Ayushman. Handcrafted with <span className='text-red-500'>❤️</span>
                </p>
                <p className='text-gray-600 dark:text-gray-400 mt-4 md:mt-0'>
                  Made with <span className='font-semibold'>Next.js</span> & <span className='font-semibold'>Tailwind CSS</span>
                </p>
              </div>
            </div>
          </div>
        </footer>
      </main>
    </div>
  )
}
