import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillGithub, AiFillLinkedin,AiFillCopyrightCircle, AiFillInstagram} from 'react-icons/ai';
import Image from "next/legacy/image";
import deved from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import Head from 'next/head'
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import finalMockupFoodApp from "../public/finalMockupFoodApp.png";
import finalMockupMovieApp from "../public/finalMockupMovieApp.png";
import MockupClock from "../public/MockupClock.png";
import mockupEbike from "../public/mockupEbike.png";
import mockupLogin from "../public/mockupLogin.png";
import finalmockupQuiz from "../public/finalmockupQuiz.png";
import finalPortfolioMockup from "../public/finalPortfolioMockup.png";
import { useState } from 'react';

export default function Home() {
  const [darkMode,setDarkMode] = useState(false);
  return (
  <div className={darkMode ? "dark" :""}>
      <Head>
        <title>Ayushman's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className=" min-h-screen ">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className='text-xl font-burtons dark:text-white font-semibold'>Portfolio</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="dark:text-white text-2xl" /></li>
              <li><button>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
               href="https://drive.google.com/file/d/1Y1oxx890C3tUxm7OkFRhcpiARhXt414K/view?usp=share_link">Resume</a>
            </button></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-3xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'>Hi! I'm Ayushman.</h2>
            <h3 className='text-2xl py-2 font-medium md:text-3xl dark:text-gray-300'>Frontend Developer and Designer</h3>
            <p className='text-md py-4 leading-8 text-gray-800 font-semibold max-w-lg mx-auto dark:text-white'>I design and code beautifully simple ideas of someones's imagination, and I love what I do.</p>
            <p className='text-xl pt-2 font-medium  dark:text-gray-200'>Living, learning, & leveling up one day at a time.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-700 dark:text-white'>
            <a className=' '
               href="https://www.linkedin.com/in/ayushman-dutt-pandey-741b391a4/"><AiFillLinkedin/></a>
            <a className=''
               href="https://www.instagram.com/ayushmanduttpandey/"><AiFillInstagram/></a>
            <a className=''
               href="https://github.com/Ayushmanpandey"><AiFillGithub/></a>
            </div>
          <div className=' relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-auto md:h-96 md:w-96'>
            <Image src={deved} width={50} height={100} layout="fill" objectFit='cover'/>
          </div>
        </section>

        {/* <!--- second page ---!> */}
        <section>
          <div>
            <h3 className='text-3xl pt-5 mt-5 font-medium dark:text-white text-center '>Services I Offer</h3>
            <h1 className=' text-justify pt-2'><span className='text-teal-500 text-xl font-medium'>Responsive design: </span></h1>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>This includes the ability of a website to adapt to different screen sizes and devices, ensuring that the site looks and functions correctly on everything from desktop computers to smartphones.</p>
            <h1 className=' text-justify pt-2'><span className='text-teal-500 text-xl font-medium'>Web design and Frontend development: </span></h1>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>This could include creating the overall look and feel of a website, as well as coding and implementing the frontend of the site using HTML, CSS, JavaScript and Frontend frameworks.</p>
            <h1 className=' text-justify pt-2'><span className='text-teal-500 text-xl font-medium'>User Interface(UI) design:</span></h1>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>It includes the design of user interfaces for software and digital products, such as websites and mobile applications. It involves creating the visual layout, look and feel, and interactive elements of a user interface, with the goal of making the product easy to use and aesthetically pleasing.
            <ul><b className='dark:text-white'>My Work Includes :-</b></ul>
            <ul><b className='dark:text-white'>Web design:</b> Creating the layout, color scheme, and other visual elements of a website, as well as designing interactive elements such as buttons and forms.</ul>
            <ul><b className='dark:text-white'>Mobile app design:</b> Designing the user interface for a mobile application, including layout, navigation, and interactive elements.</ul></p>
          </div>
          <div className='lg:flex gap-10'>
             {/* CARD 1 */}
            <div className='text-center p-10 shadow-2xl rounded-2xl my-10 dark:bg-gray-100 ring'>
              <Image src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2 flex-auto'>I value simple content structure, clean design patterns, and thoughtful interactions.</p>
              <p className='py-2 flex-auto'>Creating elegant designs suited for your needs based on design theory.</p>
              <h4 className='pt-2 text-teal-600 font-semibold'>Things I enjoy designing:</h4>
              <p className=' pt-2 gap-2'>UI design, Product design, Logo, Apps and Pamphlets</p>         


              <h4 className='pt-2 text-teal-600 font-semibold'>Design tools:</h4>           
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Adobe XD</p>
              <p className='text-gray-800 py-1'>Canva</p>
              <p className='text-gray-800 py-1'>Illustrator</p>
              <p className='text-gray-800 py-1'>Pen & Paper</p>
              <p className='text-gray-800 py-1'>Sketch</p>
              <p className='text-gray-800 py-1'>Webflow</p>
              <p className='text-gray-800 py-1'>ProtoPie</p>
            </div>
            {/* CARD 2 */}
            <div className='text-center p-10 shadow-2xl rounded-2xl my-10 dark:bg-gray-100 ring'>
              <Image src={code} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Coding the web</h3>
              <p className='py-2 flex-auto'>I like to code things from scratch, and enjoy bringing ideas to life in the browser.</p>
              <p className='py-2 flex-auto'>I also enjoy learning new frontend technologies and framework to keep myself updated.</p>
              <h4 className='pt-2 text-teal-600 font-semibold'>Technologies I code in:</h4>
              <p className=' pt-2 gap-2'>HTML, CSS, Js, React.Js and Git</p>         
              <h4 className='pt-2 text-teal-600 font-semibold'>Dev tools/Frameworks:</h4>           
              <p className='text-gray-800 py-1'>React Js</p>
              <p className='text-gray-800 py-1'>Tailwind CSS</p>
              <p className='text-gray-800 py-1'>Bootstrap</p>
              <p className='text-gray-800 py-1'>Atom</p>
              <p className='text-gray-800 py-1'>Brackets</p>
              <p className='text-gray-800 py-1'>VS Code/VS IDE</p>
              <p className='text-gray-800 py-1'>Codepen</p>
            </div>
           {/* CARD 3 */}
             <div className='text-center p-10 shadow-2xl rounded-2xl my-10  dark:bg-gray-100 ring'>
              <Image src={consulting} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Problem Solving</h3>
              <p className='py-2 flex-auto max-w-lg'>As a problem solver I use to think and create better approach for solving bugs, errors, and can see problem definition through various persepective </p>
              <p className='py-2 flex-auto max-w-lg'>Creating new approach and learning by doing makes me Generate new ideas, Implement and evaluate them, Evaluate and select the solution .</p>
              <h4 className='pt-2 text-teal-600 font-semibold'>Programming languages I try on:</h4>
              <p className=' pt-2 gap-2'>Python, CPP, C, Java,and DSA</p>         
              <h4 className='pt-2 text-teal-600 font-semibold'>Websites and Editors:</h4>           
              <p className='text-gray-800 py-1'>HackerRank</p>
              <p className='text-gray-800 py-1'>GeeksForGeeks</p>
              <p className='text-gray-800 py-1'>LeetCode</p>
              <p className='text-gray-800 py-1'>W3schools</p>
              <p className='text-gray-800 py-1'>VS Code</p>
            </div>
          </div>
        </section>
        {/* SECTION 2 */}
        <section>
          <div>
          <h3 className="text-3xl py-1 mt-5 font-medium dark:text-white text-center">My Recent Work</h3>
          <p className='text-lg font-sans text-center py-2 leading-8 text-gray-800 dark:text-gray-200'>
            Here are my projects and designs I've worked on.</p>
          <p className='text-lg font-sans text-center leading-8 text-gray-800 dark:text-gray-200'>
            Want to see more of it? 
            <button className="transition ease-in-out delay-150 rounded-lg w-28 bg-teal-500 hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300">
            <a href="mailto:payushman8@gmail.com"> Email me.</a></button>
          </p>
          </div>

          <div className='text-xl font-semibold pt-10 py-2 dark:text-gray-200'>
            <h1>My designs - </h1>
          </div>
          <div className='flex flex-col gap-10 py-2 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={finalMockupFoodApp} className='rounded-2xl object-cover width={"100%"} height={"100%"} layout="responsive" ' />
              <div className=' justify-center text-center'>
              <button className="transition ease-in-out delay-150 w-32 hover:-translate-y-1 hover:scale-110  bg-teal-500 hover:bg-indigo-500 duration-600 justify-center justify-items-center text-white font-bold py-2 px-4 rounded-2xl ring-emerald-400 ring-1  "><a href='https://github.com/Ayushmanpandey/DesigningProjects/tree/main/Food%20App%20Design%20practice'>View Project</a></button>
            </div>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={finalMockupMovieApp} className='rounded-2xl object-cover width={"100%"} height={"100%"} layout="responsive" ' />
              <div className=' justify-center text-center'>
              <button className="transition ease-in-out delay-150 w-32 hover:-translate-y-1 hover:scale-110  bg-teal-500 hover:bg-indigo-500 duration-600 justify-center justify-items-center text-white font-bold py-2 px-4 rounded-2xl ring-emerald-400 ring-1 "><a href='https://github.com/Ayushmanpandey/DesigningProjects/tree/main/MovieApp%20Figma%20redesign'>View Project</a></button>
            </div>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={MockupClock} className='rounded-2xl object-cover width={"100%"} height={"100%"} layout="responsive"' />
              <div className=' justify-center text-center'>
              <button className="transition ease-in-out delay-150 w-32 hover:-translate-y-1 hover:scale-110  bg-teal-500 hover:bg-indigo-500 duration-600 justify-center justify-items-center text-white font-bold py-2 px-4 rounded-2xl ring-emerald-400 ring-1  "><a href='https://github.com/Ayushmanpandey/DesigningProjects/tree/main/Figma%20ios%20clock%20redesign'>View Project</a></button>
            </div>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={mockupEbike} className='rounded-2xl object-cover width={"100%"} height={"100%"} layout="responsive"' />
              <div className=' justify-center text-center'>
              <button className="transition ease-in-out delay-150 w-32 hover:-translate-y-1 hover:scale-110  bg-teal-500 hover:bg-indigo-500 duration-600 justify-center justify-items-center text-white font-bold py-2 px-4 rounded-2xl ring-emerald-400 ring-1" ><a href='https://github.com/Ayushmanpandey/DesigningProjects/tree/main/figmaLandingpageDesign'>View Project</a></button>
            </div>
            </div>
          </div>

          <div className='text-xl font-semibold pt-10 py-2 dark:text-gray-200'>
            <h1>My Frontend projects - </h1>
          </div>
          <div className='flex flex-col gap-10 py-2 lg:flex-row lg:flex-wrap'>
          <div className='basis-1/3 flex-1'>
              <Image src={finalmockupQuiz} className='rounded-2xl object-cover width={"100%"} height={"100%"} layout="responsive"' />
              <div className=' justify-center text-center'>
              <button className="transition ease-in-out delay-150 w-32 hover:-translate-y-1 hover:scale-110  bg-teal-500 hover:bg-indigo-500 duration-600 justify-center justify-items-center text-white font-bold py-2 px-4 rounded-2xl ring-emerald-400 ring-1  "><a href=''>View Project</a></button>
            </div>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={mockupLogin} className='rounded-2xl object-cover width={"100%"} height={"100%"} layout="responsive"' />
              <div className=' justify-center text-center'>
              <button className="transition ease-in-out delay-150 w-32 hover:-translate-y-1 hover:scale-110  bg-teal-500 hover:bg-indigo-500 duration-600 justify-center justify-items-center text-white font-bold py-2 px-4 rounded-2xl ring-emerald-400 ring-1" ><a href='https://ayushmanpandey.github.io/Login-SignupForm/'>View Project</a></button>
            </div>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={finalPortfolioMockup} className='rounded-2xl object-cover width={"100%"} height={"100%"} layout="responsive"' />
              <div className=' justify-center text-center'>
              <button className="transition ease-in-out delay-150 w-32 hover:-translate-y-1 hover:scale-110  bg-teal-500 hover:bg-indigo-500 duration-600 justify-center justify-items-center text-white font-bold py-2 px-4 rounded-2xl ring-emerald-400 ring-1" ><a href='https://iamayushmanduttpandey.vercel.app/'>View Project</a></button>
            </div>
            </div>
          </div>
        </section>
        <footer className='text-center mb-2 text-lg flex justify-center gap-1 py-2 text-gray-600 dark:text-white'> Handcrafted by © ayushmanduttpandey
        </footer>
      </main>
    </div>
  )
}
